package com.doct24.doct24_android.model.localrepo

import com.doct24.doct24_android.model.Doctor

class LocalDoctorsRepository {

    private val doctorsList = listOf(
        Doctor(
            1,
            "doctor_nick1",
            "Джон",
            "Доу",
            "https://img.joinfo.com/i/2021/06/800x0/60d5d0d02683d.jpg",
            19,
            "Акушер",
            "Россия",
            "Москва",
            "+79999999910",
            "doctor_email1@mail.ru",
            "NO",
            "University of Oxford",
            "Кандидат наук",
            null,
            null
        ),
        Doctor(2,
            "doctor_nick2",
            "Джейн",
            "Доу",
            "https://www.theidealproduct.com/store/image/cache/catalog/image_5-800x800.jpg",
            21,
            "Анестезиолог",
            "Россия",
            "Москва",
            "+79999999911",
            "doctor_email2@mail.ru",
            "NO",
            "University of Cambridge",
            "Кандидат наук",
            null,
            null),
        Doctor(3,
            "doctor_nick3",
            "Мунго",
            "Бонам",
            "https://st44.stblizko.ru/images/product/477/974/545_original.jpg",
            56,
            "Врач общей практики",
            "Англия",
            "Лондон",
            "+79999999913",
            "doctor_email3@mail.ru",
            "NO",
            "Imperial College London",
            "Доктор наук",
            null,
            null),
        Doctor(4,
            "doctor_nick4",
            "Дин",
            "Вестерн",
            "https://miro.medium.com/max/2400/1*Z3KUtK2ioh6su0Evo6yzQw.jpeg",
            29,
            "Венеролог",
            "США",
            "Канзас",
            "+79999999914",
            "doctor_email4@mail.ru",
            "NO",
            "University College London",
            "Доктор наук",
            null,
            null),
        Doctor(5,
            "doctor_nick5",
            "Марта",
            "Джонс",
            "https://www.melomed.co.za/images/stunning2.jpg",
            26,
            "Врач спортивной медицины",
            "Англия",
            "Лондон",
            "+79999999915",
            "doctor_email5@mail.ru",
            "NO",
            "King's College London",
            "Доктор наук",
            null,
            null),
        Doctor(6,
            "doctor_nick6",
            "Джек",
            "Харкнесс",
            "https://i.pinimg.com/736x/3d/f8/a9/3df8a9b0de1e332e5faf464950f434e3.jpg",
            32,
            "Аллерголог",
            "Уэльс",
            "Кардифф",
            "+79999999916",
            "doctor_email6@mail.ru",
            "NO",
            "Karolinska Institute",
            "Кандидат наук",
            null,
            null),
        Doctor(7,
            "doctor_nick7",
            "Доктор",
            "Кто",
            "https://www.shropshirestar.com/resizer/25QCrirXw3KnEylmGg9_YLvNoPA=/1200x0/cloudfront-us-east-1.images.arcpublishing.com/mna/FL3FCII5VZDXTP4GVJK3MOGYOU.jpg",
            3000,
            "Врач общей практики",
            "Галлифрей",
            "Аркадия",
            "+79999999917",
            "doctor_email7@mail.ru",
            "NO",
            "Universität Heidelberg",
            "Доктор наук",
            null,
            null),
    )

    fun getDoctorsList() = doctorsList
}